//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctEXPERIENCIAS
    {
        public int intEXPERIENCIA { get; set; }
        public string strEXPERIENCIA { get; set; }
        public Nullable<float> rlPESO { get; set; }
        public Nullable<bool> btHAB { get; set; }
    }
}
