//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        public Nullable<int> Productoid { get; set; }
        public string FICHAS { get; set; }
        public int Fichaid { get; set; }
        public string Fichas_Link { get; set; }
    }
}
