//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaComercial
    {
        public Nullable<int> Fichaid { get; set; }
        public string GUIAS { get; set; }
        public int Guiaid { get; set; }
        public string LinkGuia { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
