//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionCredito.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POCEntities : DbContext
    {
        public POCEntities()
            : base("name=POCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTROL> CONTROL { get; set; }
        public virtual DbSet<ctACCIONES> ctACCIONES { get; set; }
        public virtual DbSet<ctEXPERIENCIAS> ctEXPERIENCIAS { get; set; }
        public virtual DbSet<ctFLUJOS_CAJA> ctFLUJOS_CAJA { get; set; }
        public virtual DbSet<ctNCPS> ctNCPS { get; set; }
        public virtual DbSet<ctRATINGS> ctRATINGS { get; set; }
        public virtual DbSet<ctRESULTADOS> ctRESULTADOS { get; set; }
        public virtual DbSet<ctSECTORES> ctSECTORES { get; set; }
        public virtual DbSet<ctVARIABLES> ctVARIABLES { get; set; }
        public virtual DbSet<Repositorio_ClientesJuridicos> Repositorio_ClientesJuridicos { get; set; }
        public virtual DbSet<TRX> TRX { get; set; }
        public virtual DbSet<Repositorio_AgenciasBNCR> Repositorio_AgenciasBNCR { get; set; }
    
        public virtual ObjectResult<PROC_PRORROGA_EMPRESAS_Result> PROC_PRORROGA_EMPRESAS(Nullable<int> intEXPERIENCIA, Nullable<int> intRATING, Nullable<int> intACCIONES, Nullable<int> intSECTOR, Nullable<int> intNCP, Nullable<int> intFLUJO_CAJA)
        {
            var intEXPERIENCIAParameter = intEXPERIENCIA.HasValue ?
                new ObjectParameter("intEXPERIENCIA", intEXPERIENCIA) :
                new ObjectParameter("intEXPERIENCIA", typeof(int));
    
            var intRATINGParameter = intRATING.HasValue ?
                new ObjectParameter("intRATING", intRATING) :
                new ObjectParameter("intRATING", typeof(int));
    
            var intACCIONESParameter = intACCIONES.HasValue ?
                new ObjectParameter("intACCIONES", intACCIONES) :
                new ObjectParameter("intACCIONES", typeof(int));
    
            var intSECTORParameter = intSECTOR.HasValue ?
                new ObjectParameter("intSECTOR", intSECTOR) :
                new ObjectParameter("intSECTOR", typeof(int));
    
            var intNCPParameter = intNCP.HasValue ?
                new ObjectParameter("intNCP", intNCP) :
                new ObjectParameter("intNCP", typeof(int));
    
            var intFLUJO_CAJAParameter = intFLUJO_CAJA.HasValue ?
                new ObjectParameter("intFLUJO_CAJA", intFLUJO_CAJA) :
                new ObjectParameter("intFLUJO_CAJA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_PRORROGA_EMPRESAS_Result>("PROC_PRORROGA_EMPRESAS", intEXPERIENCIAParameter, intRATINGParameter, intACCIONESParameter, intSECTORParameter, intNCPParameter, intFLUJO_CAJAParameter);
        }
    }
}
