//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repositorio_ClientesJuridicos
    {
        public int CLI_CODIGO_CLIENTE { get; set; }
        public byte TPI_CODIGO_IDENTIFICACION { get; set; }
        public string CLI_IDENTIFICACION { get; set; }
        public string ID_SUGEF { get; set; }
        public string CFI_NOMBRE { get; set; }
    }
}
