//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repositorio_AgenciasBNCR
    {
        public int Oficina_Codigo { get; set; }
        public string Oficina_Descripcion { get; set; }
        public Nullable<int> Id_Zona { get; set; }
    }
}
