//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX
    {
        public int intTRX { get; set; }
        public Nullable<decimal> numCLIENTE { get; set; }
        public Nullable<System.DateTime> dtFECHA_APLICACION { get; set; }
        public Nullable<int> intOFICINA { get; set; }
        public string strUSUARIO { get; set; }
        public Nullable<bool> btHAB { get; set; }
        public Nullable<int> intEXPERIENCIA { get; set; }
        public Nullable<int> intRATING { get; set; }
        public Nullable<int> intACCIONES { get; set; }
        public Nullable<int> intSECTOR { get; set; }
        public Nullable<int> intNCP { get; set; }
        public int intFLUJO_CAJA { get; set; }
        public Nullable<int> intRESULTADO { get; set; }
        public string strRESULTADO { get; set; }
    }
}
