//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DireccionCredito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitas
    {
        public string UsuarioWindows { get; set; }
        public string Email { get; set; }
        public string NombreCompleto { get; set; }
        public string Empleado { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Oficina { get; set; }
        public string Pic { get; set; }
        public int Consecutivo { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string ProductoBuscado { get; set; }
        public string Actividad { get; set; }
        public string Tipo { get; set; }
        public string Garantía { get; set; }
        public string GuiaComercial { get; set; }
    }
}
